### ISSUE TITLE
com.hendraanggrian.widget.SocialTextView not working with   userNameTextView.setText(Html.fromHtml("<b>" +"Hello+"</b>"));

### ISSUE THREAD

**Issue by GotesoDeveloper** [hendraanggrian/socialview#43] opened 2018-07-19 03:59 UTC

**Comment by hendraanggrian** [comment] 2018-11-27 14:30
Duplicate of #40.

**Closed by hendraanggrian** 2018-11-27 14:30 UTC

**Comment by FidaMOhsin** [comment] 2020-12-09 05:34
Hi @hendraanggrian 
Can you please tell me have you fixed this issue?
