### ISSUE TITLE
Show tag list of all members without filtering after just adding @

### ISSUE THREAD

**Issue by FidaMOhsin** [hendraanggrian/socialview#94] opened 2020-12-23 09:27 UTC
How can we show tag list of all members without filtering after just adding @?
Because for now tag list is coming when we write something after adding @. But now I want all list first when I will just write @.
Any help?

**Comment by hendraanggrian** [comment] 2021-06-08 18:58
Duplicate of #23.

Though depending on your AndroidX version, putting `android:completionThreshold="0"` to your `SocialAutoCompleteTextView` XML may do the trick.

**Closed by hendraanggrian** 2021-06-08 18:58 UTC
